name: chem_utils

channels:
  - conda-forge
  - rdkit

dependencies:
  - python>=3.10
  - matplotlib
  - numpy
  - pandas
  - pip
  - rdkit
  - scikit-learn
  - scikit-learn-intelex
  - tqdm
  - umap-learn
  - pip:
      - typed-argument-parser
