name: chem_utils

channels:
  - conda-forge
  - rdkit

dependencies:
  - python>=3.10
  - matplotlib
  - numpy
  - pandas
  - pip
  - rdkit
  - scikit-learn
  - tqdm
  - pip:
    - descriptastorus
    - typed-argument-parser>=1.8.0
