name: chem_utils

channels:
  - conda-forge
  - rdkit

dependencies:
  - python>=3.9
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pip
  - rdkit
  - scikit-learn
  - tqdm
  - pip:
      - typed-argument-parser
